version: '3.8'

# Services pour le déploiement complet de la solution FHIRHub + HAPI FHIR
services:
  # Service FHIRHub - Application de conversion HL7v2 vers FHIR
  fhirhub:
    build:
      context: .
      dockerfile: Dockerfile
    image: fhirhub:latest
    container_name: fhirhub
    restart: unless-stopped
    ports:
      - "5000:5000"  # Exposition du port du serveur web FHIRHub
    volumes:
      # Volumes pour la persistance des données même après redémarrage/reconstruction des conteneurs
      - ./data/fhirhub/storage:/app/storage       # Base de données SQLite et caches
      - ./data/fhirhub/french_terminology:/app/french_terminology  # Terminologies médicales françaises
      - ./data/fhirhub/logs:/app/logs             # Logs d'application
      - ./data/fhirhub/temp:/app/temp             # Fichiers temporaires
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HAPI_FHIR_URL=http://hapi-fhir:8080/fhir  # URL du serveur HAPI FHIR (résolution DNS interne par Docker)
    depends_on:
      - hapi-fhir  # S'assure que le service HAPI FHIR démarre avant FHIRHub
    networks:
      - fhir-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Service HAPI FHIR - Serveur FHIR R4
  hapi-fhir:
    image: hapiproject/hapi:latest  # Utilisation de l'image officielle HAPI FHIR
    container_name: hapi-fhir
    restart: unless-stopped
    ports:
      - "8080:8080"  # Exposition du port du serveur HAPI FHIR
    volumes:
      # Volume pour la persistance des données H2 (base de données par défaut de HAPI FHIR)
      - ./data/hapi-fhir:/data/hapi
    environment:
      - hapi.fhir.default_encoding=json           # Format par défaut des réponses
      - hapi.fhir.fhir_version=R4                 # Version FHIR utilisée (R4 = 4.0.1)
      - spring.datasource.url=jdbc:h2:/data/hapi/database/h2.db  # Chemin de la base de données H2
      - hapi.fhir.allow_external_references=true  # Autorise les références externes
      - hapi.fhir.allow_multiple_delete=true      # Autorise les suppressions multiples
      - hapi.fhir.server_address=http://localhost:8080/fhir  # URL serveur pour les liens de pagination
    networks:
      - fhir-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fhir/metadata"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Le serveur HAPI FHIR peut prendre du temps à démarrer

# Réseau partagé entre les services
networks:
  fhir-network:
    driver: bridge

# Volumes persistants pour stocker les données en dehors des conteneurs
volumes:
  fhirhub-storage:
    driver: local
  hapi-fhir-data:
    driver: local